import java.util.HashMap;

public class Tabela {
  public HashMap<String, Simbolo> tabela = new HashMap<>();

  public final byte sublinhado = 0;
  public final byte ponto = 1;
  public final byte virgula = 2;
  public final byte ponto_virgula = 3;
  public final byte dois_pontos = 4;
  public final byte parenteses_esq = 5;
  public final byte parenteses_dir = 6;
  public final byte chave_esq = 7;
  public final byte chave_dir = 8;
  public final byte colchete_esq = 9;
  public final byte colchete_dir = 10;
  public final byte mais = 11;
  public final byte menos = 12;
  public final byte aspas = 13;
  public final byte apostrofo = 14;
  public final byte arroba = 15;
  public final byte ecomercial = 16;
  public final byte porcentagem = 17;
  public final byte exclamacao = 18;
  public final byte interrogacao = 19;
  public final byte maior = 20;
  public final byte menor = 21;
  public final byte igual = 22;
  public final byte igual_igual = 23;
  public final byte asterisco = 24;
  public final byte maior_igual = 25;
  public final byte menor_igual = 26;
  public final byte diferente = 27;
  public final byte barra = 28;
  public final byte quociente = 29;
  public final byte CONST = 30;
  public final byte INT = 31;
  public final byte CHAR = 32;
  public final byte WHILE = 33;
  public final byte IF = 34;
  public final byte REAL = 35;
  public final byte ELSE = 36;
  public final byte AND = 37;
  public final byte OR = 38;
  public final byte NOT = 39;
  public final byte begin = 40;
  public final byte end = 41;
  public final byte readln = 42;
  public final byte string = 43;
  public final byte write = 44;
  public final byte writeln = 45;
  public final byte TRUE = 46;
  public final byte FALSE = 47;
  public final byte BOOLEAN = 48;
  public final byte ID = 49;
}